server:
  port: 8087

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: persona-service
          uri: lb://persona-service
          predicates:
            - Path=/api/persona/**
          filters:
            - RewritePath= /api/(?<persona>.*), /$\{persona}
            
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    preferIpAddress: true      
      